"""
LinkedIn Agent — Draft Generator
Creates professional LinkedIn post drafts about Multicraft Agency
and Lyvexa AI services, saved to Drafts/LinkedIn_Post.md.
"""

import sys
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent
DRAFTS_DIR = BASE_DIR / "Drafts"

# Service catalog for generating varied posts
SERVICES = {
    "multicraft_agency": {
        "name": "Multicraft Agency",
        "tagline": "Building Digital Futures",
        "services": [
            "Custom Web & Mobile App Development",
            "AI-Powered Business Automation",
            "Brand Identity & UI/UX Design",
            "Cloud Architecture & DevOps",
            "E-Commerce Solutions",
        ],
        "cta": "Let's build something extraordinary together.",
    },
    "lyvexa_ai": {
        "name": "Lyvexa AI",
        "tagline": "Intelligence That Works For You",
        "services": [
            "AI Employee Agents (Digital FTEs)",
            "Autonomous Email & Task Management",
            "Real-Time Business Intelligence Dashboards",
            "Custom LLM Integration & Fine-Tuning",
            "Workflow Automation with Human-in-the-Loop",
        ],
        "cta": "Ready to hire your first AI employee?",
    },
}


def generate_post(brand_key, topic=None):
    """Generate a LinkedIn post draft for the given brand."""
    brand = SERVICES.get(brand_key)
    if not brand:
        print(f"[ERROR] Unknown brand: {brand_key}")
        return None

    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d %H:%M")

    services_list = "\n".join(f"  - {s}" for s in brand["services"])

    if topic:
        hook = f"We've been working on something exciting: **{topic}**."
    else:
        hook = f"In 2026, automation isn't optional — it's the competitive edge."

    content = f"""# LinkedIn Post Draft — {brand['name']}

- **Brand:** {brand['name']}
- **Tagline:** {brand['tagline']}
- **Generated:** {date_str}
- **Status:** Draft

---

{hook}

At **{brand['name']}**, we specialize in turning complex challenges into elegant solutions:

{services_list}

The future belongs to businesses that move fast and build smart. We help you do both.

**{brand['cta']}**

---

#AI #Automation #DigitalTransformation #{brand['name'].replace(' ', '')} #BuildInPublic #2026

---

> Auto-generated by LinkedIn Agent — AI Employee Vault
> Review and personalize before posting.
"""
    return content


def save_draft(content, brand_key):
    """Save the draft to Drafts/ folder."""
    DRAFTS_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"LinkedIn_Post_{brand_key}_{timestamp}.md"
    filepath = DRAFTS_DIR / filename

    filepath.write_text(content, encoding="utf-8")
    return filepath


def main():
    print("=" * 50)
    print("  LinkedIn Agent — Post Draft Generator")
    print("=" * 50)
    print()

    # Parse arguments
    brand_key = "multicraft_agency"
    topic = None

    if "--lyvexa" in sys.argv:
        brand_key = "lyvexa_ai"
    if "--both" in sys.argv:
        for key in SERVICES:
            content = generate_post(key)
            path = save_draft(content, key)
            print(f"  [SAVED] {path.name}")
        print(f"\n[DONE] Drafts saved to {DRAFTS_DIR}")
        return

    for arg in sys.argv[1:]:
        if not arg.startswith("--"):
            topic = arg

    content = generate_post(brand_key, topic)
    if content:
        path = save_draft(content, brand_key)
        print(f"  [SAVED] {path.name}")
        print(f"  [PATH] {path}")
        print(f"\n[DONE] Draft saved to {DRAFTS_DIR}")


if __name__ == "__main__":
    main()
