"""
Odoo MCP Bridge — Platinum Tier Accounting Agent
Connects to Odoo 18/19 Community via JSON-RPC (future),
currently reads mock data from accounting_status.json.
Generates an Accounting Audit summary and flags overdue invoices as tasks.
"""

import json
import sys
import time
import re
from pathlib import Path
from datetime import datetime, date

BASE_DIR = Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "accounting_status.json"
READINGS_DIR = BASE_DIR / "Readings"
TASKS_DIR = BASE_DIR / "Needs_Action"
POLL_INTERVAL = 600  # seconds (10 minutes)

# ──────────────────────────────────────────────
# ODOO JSON-RPC PLACEHOLDER
# ──────────────────────────────────────────────
# Future implementation will replace load_mock_data() with:
#
# ODOO_URL = "http://localhost:8069"
# ODOO_DB = "multicraft"
# ODOO_USER = "admin"
# ODOO_PASS = "admin"
#
# def odoo_authenticate():
#     payload = {
#         "jsonrpc": "2.0",
#         "method": "call",
#         "params": {
#             "service": "common",
#             "method": "login",
#             "args": [ODOO_DB, ODOO_USER, ODOO_PASS]
#         }
#     }
#     resp = requests.post(f"{ODOO_URL}/jsonrpc", json=payload)
#     return resp.json()["result"]
#
# def odoo_fetch_invoices(uid):
#     payload = {
#         "jsonrpc": "2.0",
#         "method": "call",
#         "params": {
#             "service": "object",
#             "method": "execute_kw",
#             "args": [ODOO_DB, uid, ODOO_PASS,
#                      "account.move", "search_read",
#                      [[["move_type", "=", "out_invoice"]]],
#                      {"fields": ["name","partner_id","amount_total",
#                                  "invoice_date","invoice_date_due",
#                                  "payment_state","state"],
#                       "limit": 50}]
#         }
#     }
#     resp = requests.post(f"{ODOO_URL}/jsonrpc", json=payload)
#     return resp.json()["result"]
# ──────────────────────────────────────────────


def load_data():
    """Load accounting data (mock or future Odoo)."""
    if not DATA_FILE.exists():
        print(f"  [ERROR] {DATA_FILE.name} not found.")
        return None
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def fmt_pkr(amount):
    """Format a number as PKR currency string."""
    return f"PKR {amount:,.0f}"


def sanitize_filename(name):
    return re.sub(r'[<>:"/\\|?*]', '', name).strip().replace(' ', '_')[:80]


def analyze_invoices(invoices):
    """Compute invoice analytics."""
    total_revenue = sum(i["amount"] for i in invoices)
    paid = [i for i in invoices if i["status"] == "paid"]
    pending = [i for i in invoices if i["status"] == "pending"]
    overdue = [i for i in invoices if i["status"] == "overdue"]
    draft = [i for i in invoices if i["status"] == "draft"]

    collected = sum(i["amount"] for i in paid)
    outstanding = sum(i["amount"] for i in pending + overdue)
    overdue_total = sum(i["amount"] for i in overdue)

    return {
        "total_revenue": total_revenue,
        "collected": collected,
        "outstanding": outstanding,
        "overdue_total": overdue_total,
        "paid": paid,
        "pending": pending,
        "overdue": overdue,
        "draft": draft,
        "collection_rate": (collected / total_revenue * 100) if total_revenue > 0 else 0,
    }


def analyze_expenses(expenses):
    """Compute expense analytics by category."""
    total = sum(e["amount"] for e in expenses)
    by_category = {}
    for e in expenses:
        cat = e["category"]
        by_category[cat] = by_category.get(cat, 0) + e["amount"]
    return {
        "total": total,
        "by_category": dict(sorted(by_category.items(), key=lambda x: x[1], reverse=True)),
    }


def generate_audit(data):
    """Generate Readings/Accounting_Audit.md."""
    READINGS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    invoices = data.get("invoices", [])
    expenses = data.get("expenses", [])
    bank = data.get("bank_balance", {})
    inv = analyze_invoices(invoices)
    exp = analyze_expenses(expenses)

    net_profit = inv["collected"] - exp["total"]
    profit_margin = (net_profit / inv["collected"] * 100) if inv["collected"] > 0 else 0

    lines = [
        "# Accounting Audit Report",
        "",
        f"- **Company:** {data.get('company', 'N/A')}",
        f"- **Period:** {data.get('fiscal_month', 'N/A')}",
        f"- **Generated:** {now}",
        f"- **Data Source:** accounting_status.json (Mock — Odoo bridge pending)",
        f"- **Status:** Auto-generated by Odoo MCP Bridge",
        "",
        "---",
        "",
        "## Financial Overview",
        "",
        "| Metric | Amount |",
        "|--------|--------|",
        f"| Total Invoiced | {fmt_pkr(inv['total_revenue'])} |",
        f"| Collected (Paid) | {fmt_pkr(inv['collected'])} |",
        f"| Outstanding | {fmt_pkr(inv['outstanding'])} |",
        f"| Overdue | {fmt_pkr(inv['overdue_total'])} |",
        f"| Total Expenses | {fmt_pkr(exp['total'])} |",
        f"| **Net Profit (Collected - Expenses)** | **{fmt_pkr(net_profit)}** |",
        f"| Collection Rate | {inv['collection_rate']:.1f}% |",
        f"| Profit Margin | {profit_margin:.1f}% |",
        f"| Bank Balance | {fmt_pkr(bank.get('balance', 0))} ({bank.get('as_of', 'N/A')}) |",
        "",
        "---",
        "",
        "## Invoice Breakdown",
        "",
        "| ID | Client | Description | Amount | Status | Due Date |",
        "|-----|--------|-------------|--------|--------|----------|",
    ]

    status_icon = {"paid": "Paid", "pending": "Pending", "overdue": "**OVERDUE**", "draft": "Draft"}
    for i in invoices:
        s = status_icon.get(i["status"], i["status"])
        due = i.get("due_date") or "TBD"
        lines.append(f"| {i['id']} | {i['client']} | {i['description'][:40]} | {fmt_pkr(i['amount'])} | {s} | {due} |")

    lines += [
        "",
        "---",
        "",
        "## Expense Breakdown by Category",
        "",
        "| Category | Amount | % of Total |",
        "|----------|--------|------------|",
    ]

    for cat, amt in exp["by_category"].items():
        pct = (amt / exp["total"] * 100) if exp["total"] > 0 else 0
        lines.append(f"| {cat} | {fmt_pkr(amt)} | {pct:.1f}% |")

    lines.append(f"| **Total** | **{fmt_pkr(exp['total'])}** | **100%** |")

    lines += [
        "",
        "---",
        "",
        "## Expense Details",
        "",
        "| ID | Vendor | Description | Category | Amount | Status |",
        "|----|--------|-------------|----------|--------|--------|",
    ]

    for e in expenses:
        lines.append(f"| {e['id']} | {e['vendor']} | {e['description'][:35]} | {e['category']} | {fmt_pkr(e['amount'])} | {e['status'].capitalize()} |")

    # AI Recommendations
    lines += [
        "",
        "---",
        "",
        "## AI Recommendations",
        "",
    ]

    if inv["overdue"]:
        lines.append(f"**1. URGENT — Overdue Invoices ({fmt_pkr(inv['overdue_total'])})**")
        for i in inv["overdue"]:
            days = (date.today() - date.fromisoformat(i["due_date"])).days
            lines.append(f"   - {i['id']} ({i['client']}): {days} days overdue — send payment reminder immediately")
        lines.append("")

    if inv["pending"]:
        lines.append(f"**2. Follow Up — Pending Invoices ({fmt_pkr(sum(i['amount'] for i in inv['pending']))})**")
        for i in inv["pending"]:
            lines.append(f"   - {i['id']} ({i['client']}): due {i['due_date']} — monitor and send reminder 3 days before due")
        lines.append("")

    if inv["draft"]:
        lines.append(f"**3. Finalize Drafts**")
        for i in inv["draft"]:
            lines.append(f"   - {i['id']} ({i['client']}): draft invoice — finalize and send to client")
        lines.append("")

    top_expense = list(exp["by_category"].keys())[0] if exp["by_category"] else None
    if top_expense:
        lines.append(f"**4. Expense Watch:** Largest category is **{top_expense}** ({fmt_pkr(exp['by_category'][top_expense])}). Review for optimization opportunities.")
        lines.append("")

    lines += [
        "---",
        "",
        "> Auto-generated by Odoo MCP Bridge — AI Employee Vault",
    ]

    audit_path = READINGS_DIR / "Accounting_Audit.md"
    audit_path.write_text("\n".join(lines), encoding="utf-8")
    return audit_path


def create_overdue_tasks(data):
    """Create tasks in Needs_Action/ for overdue invoices."""
    TASKS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    created = []

    for inv in data.get("invoices", []):
        if inv["status"] != "overdue":
            continue

        safe_name = sanitize_filename(inv["id"])
        filename = f"ACCT_TASK_{safe_name}.md"
        filepath = TASKS_DIR / filename

        if filepath.exists():
            continue

        days_overdue = (date.today() - date.fromisoformat(inv["due_date"])).days

        content = f"""# Accounting Task: Overdue Invoice {inv['id']}

- **Priority:** HIGH
- **Client:** {inv['client']}
- **Invoice:** {inv['id']}
- **Amount:** {fmt_pkr(inv['amount'])}
- **Due Date:** {inv['due_date']}
- **Days Overdue:** {days_overdue}
- **Detected:** {now}
- **Status:** Pending

---

## AI Suggested Action

Send an immediate payment reminder to {inv['client']} for invoice {inv['id']} ({fmt_pkr(inv['amount'])}). If no response within 48 hours, escalate with a follow-up call.

---

## Invoice Details

- **Description:** {inv['description']}
- **Issued:** {inv['issue_date']}
- **Due:** {inv['due_date']}
- **Amount:** {fmt_pkr(inv['amount'])}

---

> Auto-generated by Odoo MCP Bridge — AI Employee Vault
"""
        filepath.write_text(content, encoding="utf-8")
        created.append(filename)

    return created


def run_scan():
    """Run a single audit cycle."""
    now = datetime.now().strftime("%H:%M:%S")
    print(f"\n[{now}] Running accounting audit...")

    data = load_data()
    if not data:
        return 0

    invoices = data.get("invoices", [])
    expenses = data.get("expenses", [])
    print(f"  [SCAN] {len(invoices)} invoices, {len(expenses)} expenses loaded")

    # Generate audit
    audit_path = generate_audit(data)
    overdue_count = sum(1 for i in invoices if i["status"] == "overdue")
    print(f"  [AUDIT] {audit_path.name} (overdue: {overdue_count})")

    # Create tasks for overdue invoices
    created = create_overdue_tasks(data)
    for f in created:
        print(f"  [TASK] {f}")

    if not created:
        print("  [OK] All overdue tasks already exist. Nothing new.")
    else:
        print(f"  [DONE] Created {len(created)} overdue task(s).")

    return len(created)


def main():
    print("=" * 50)
    print("  Odoo MCP Bridge — Accounting Agent")
    print("=" * 50)
    print(f"  Vault:    {BASE_DIR}")
    print(f"  Data:     {DATA_FILE}")
    print(f"  Company:  Multicraft Agency")
    print()
    print("  [MODE] Mock data — Odoo JSON-RPC integration pending")
    print()

    # Single-run mode
    if "--once" in sys.argv:
        run_scan()
        print("\nDone (single run).")
        return

    # Continuous loop mode
    print(f"[LOOP] Auditing every {POLL_INTERVAL}s (10 min). Press Ctrl+C to stop.\n")
    while True:
        try:
            run_scan()
        except KeyboardInterrupt:
            print("\n[STOP] Stopped by user.")
            break
        except Exception as e:
            print(f"  [ERROR] {e} — retrying in {POLL_INTERVAL}s...")

        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
