"""
Social Media Agent — Platinum Tier
Fetches social media updates from social_updates.json (mock data),
generates a summary in Readings/Social_Summary.md, and creates
tasks in Needs_Action/Social/ for business inquiries.
"""

import json
import sys
import time
import re
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "social_updates.json"
READINGS_DIR = BASE_DIR / "Readings"
SOCIAL_TASKS_DIR = BASE_DIR / "Needs_Action" / "Social"
POLL_INTERVAL = 300  # seconds (5 minutes)


def load_social_data():
    """Load mock social media data from JSON."""
    if not DATA_FILE.exists():
        print(f"  [ERROR] {DATA_FILE.name} not found.")
        return None
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def sanitize_filename(name):
    """Remove characters invalid in filenames."""
    return re.sub(r'[<>:"/\\|?*]', '', name).strip().replace(' ', '_')[:80]


def classify_message(msg):
    """Return a priority and response hint for a message."""
    if msg.get("is_business_inquiry"):
        return "HIGH", suggest_response(msg)
    return "LOW", None


def suggest_response(msg):
    """Generate a one-line suggested response for a business inquiry."""
    content = msg.get("content", "").lower()
    sender = msg.get("from", "Unknown")

    if any(w in content for w in ["rate", "price", "cost", "budget", "quote"]):
        return f"Send {sender} the Multicraft Agency services & pricing deck"
    if any(w in content for w in ["call", "schedule", "meeting", "consult"]):
        return f"Schedule a discovery call with {sender} via Calendly"
    if any(w in content for w in ["app", "website", "mobile", "web"]):
        return f"Share portfolio and discuss project scope with {sender}"
    if any(w in content for w in ["partner", "collaboration", "automation", "ai"]):
        return f"Arrange a Lyvexa AI consultation session with {sender}"
    return f"Follow up with {sender} to understand their requirements"


def generate_summary(data):
    """Generate Readings/Social_Summary.md from social data."""
    READINGS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        "# Social Media Summary",
        f"- **Generated:** {now}",
        f"- **Data Source:** social_updates.json",
        f"- **Status:** Auto-generated by Social Media Agent",
        "",
        "---",
        "",
    ]

    total_messages = 0
    total_inquiries = 0
    total_notifications = 0

    for platform, pdata in data.get("platforms", {}).items():
        platform_title = platform.capitalize()
        messages = pdata.get("messages", [])
        notifications = pdata.get("notifications", [])
        inquiries = [m for m in messages if m.get("is_business_inquiry")]

        total_messages += len(messages)
        total_inquiries += len(inquiries)
        total_notifications += len(notifications)

        lines.append(f"## {platform_title}")
        lines.append("")
        lines.append(f"**Messages:** {len(messages)} | **Business Inquiries:** {len(inquiries)} | **Notifications:** {len(notifications)}")
        lines.append("")

        # Messages table
        if messages:
            lines.append("### Messages")
            lines.append("")
            lines.append("| From | Type | Time | Business? | Preview |")
            lines.append("|------|------|------|-----------|---------|")
            for m in messages:
                biz = "Yes" if m.get("is_business_inquiry") else "No"
                preview = m.get("content", "")[:60] + ("..." if len(m.get("content", "")) > 60 else "")
                lines.append(f"| {m['from']} | {m['type']} | {m['timestamp']} | **{biz}** | {preview} |")
            lines.append("")

        # Notifications
        if notifications:
            lines.append("### Notifications")
            lines.append("")
            for n in notifications:
                lines.append(f"- **{n['type']}** ({n['timestamp']}): {n['content']}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Stats block
    lines.insert(7, f"## Overview")
    lines.insert(8, "")
    lines.insert(9, f"| Metric | Count |")
    lines.insert(10, f"|--------|-------|")
    lines.insert(11, f"| Total Messages | {total_messages} |")
    lines.insert(12, f"| Business Inquiries | {total_inquiries} |")
    lines.insert(13, f"| Notifications | {total_notifications} |")
    lines.insert(14, "")
    lines.insert(15, "---")
    lines.insert(16, "")

    lines.append("> Auto-generated by Social Media Agent — AI Employee Vault")

    summary_path = READINGS_DIR / "Social_Summary.md"
    summary_path.write_text("\n".join(lines), encoding="utf-8")
    return summary_path, total_inquiries


def create_inquiry_tasks(data):
    """Create task files in Needs_Action/Social/ for business inquiries."""
    SOCIAL_TASKS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    created = []

    for platform, pdata in data.get("platforms", {}).items():
        platform_title = platform.capitalize()
        for msg in pdata.get("messages", []):
            if not msg.get("is_business_inquiry"):
                continue

            safe_name = sanitize_filename(f"{platform}_{msg['from']}")
            filename = f"SOCIAL_TASK_{safe_name}.md"
            filepath = SOCIAL_TASKS_DIR / filename

            if filepath.exists():
                continue

            priority, response_hint = classify_message(msg)

            content = f"""# Social Task: {msg['from']} — {platform_title}

- **Priority:** {priority}
- **Platform:** {platform_title}
- **From:** {msg['from']}
- **Type:** {msg['type']}
- **Received:** {msg['timestamp']}
- **Detected:** {now}
- **Status:** Pending

---

## Original Message

> {msg['content']}

---

## AI Suggested Action

{response_hint}

---

> Auto-generated by Social Media Agent — AI Employee Vault
"""
            filepath.write_text(content, encoding="utf-8")
            created.append(filename)

    return created


def run_scan():
    """Run a single scan cycle."""
    now = datetime.now().strftime("%H:%M:%S")
    print(f"\n[{now}] Scanning social media updates...")

    data = load_social_data()
    if not data:
        return 0

    platforms = data.get("platforms", {})
    total_msgs = sum(len(p.get("messages", [])) for p in platforms.values())
    print(f"  [SCAN] Loaded {total_msgs} messages across {len(platforms)} platforms")

    # Generate summary
    summary_path, inquiry_count = generate_summary(data)
    print(f"  [SUMMARY] {summary_path.name} ({inquiry_count} business inquiries)")

    # Create tasks for inquiries
    created = create_inquiry_tasks(data)
    for f in created:
        print(f"  [TASK] {f}")

    if not created:
        print("  [OK] All inquiry tasks already exist. Nothing new.")
    else:
        print(f"  [DONE] Created {len(created)} new social task(s).")

    return len(created)


def main():
    print("=" * 50)
    print("  Social Media Agent — Platinum Tier")
    print("=" * 50)
    print(f"  Vault:  {BASE_DIR}")
    print(f"  Data:   {DATA_FILE}")
    print(f"  Tasks:  {SOCIAL_TASKS_DIR}")
    print()

    # Single-run mode
    if "--once" in sys.argv:
        run_scan()
        print("\nDone (single run).")
        return

    # Continuous loop mode
    print(f"[LOOP] Scanning every {POLL_INTERVAL}s (5 min). Press Ctrl+C to stop.\n")
    while True:
        try:
            run_scan()
        except KeyboardInterrupt:
            print("\n[STOP] Stopped by user.")
            break
        except Exception as e:
            print(f"  [ERROR] {e} — retrying in {POLL_INTERVAL}s...")

        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
